//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ChampionshipId"/&gt;
 *         &lt;element ref="{}Name"/&gt;
 *         &lt;element ref="{}ChampionshipType"/&gt;
 *         &lt;element ref="{}ChampionshipDiscipline"/&gt;
 *         &lt;element ref="{}AgeGroup"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "championshipId",
    "name",
    "championshipType",
    "championshipDiscipline",
    "ageGroup"
})
@XmlRootElement(name = "Championship")
public class Championship {

    @XmlElement(name = "ChampionshipId", required = true)
    protected ChampionshipId championshipId;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "ChampionshipType", required = true)
    protected ChampionshipType championshipType;
    @XmlElement(name = "ChampionshipDiscipline", required = true)
    protected ChampionshipDiscipline championshipDiscipline;
    @XmlElement(name = "AgeGroup", required = true)
    protected AgeGroup ageGroup;

    /**
     * Gets the value of the championshipId property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipId }
     *     
     */
    public ChampionshipId getChampionshipId() {
        return championshipId;
    }

    /**
     * Sets the value of the championshipId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipId }
     *     
     */
    public void setChampionshipId(ChampionshipId value) {
        this.championshipId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the championshipType property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipType }
     *     
     */
    public ChampionshipType getChampionshipType() {
        return championshipType;
    }

    /**
     * Sets the value of the championshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipType }
     *     
     */
    public void setChampionshipType(ChampionshipType value) {
        this.championshipType = value;
    }

    /**
     * Gets the value of the championshipDiscipline property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipDiscipline }
     *     
     */
    public ChampionshipDiscipline getChampionshipDiscipline() {
        return championshipDiscipline;
    }

    /**
     * Sets the value of the championshipDiscipline property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipDiscipline }
     *     
     */
    public void setChampionshipDiscipline(ChampionshipDiscipline value) {
        this.championshipDiscipline = value;
    }

    /**
     * Gets the value of the ageGroup property.
     * 
     * @return
     *     possible object is
     *     {@link AgeGroup }
     *     
     */
    public AgeGroup getAgeGroup() {
        return ageGroup;
    }

    /**
     * Sets the value of the ageGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeGroup }
     *     
     */
    public void setAgeGroup(AgeGroup value) {
        this.ageGroup = value;
    }

}
