//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ChampionshipResultlistId"/&gt;
 *         &lt;element ref="{}ChampionshipRaceSubType"/&gt;
 *         &lt;element ref="{}ClassResult" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="raceClassName" default="NotSet"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Men"/&gt;
 *             &lt;enumeration value="Women"/&gt;
 *             &lt;enumeration value="OClass"/&gt;
 *             &lt;enumeration value="PClass"/&gt;
 *             &lt;enumeration value="Mixed"/&gt;
 *             &lt;enumeration value="Men-18"/&gt;
 *             &lt;enumeration value="Women-18"/&gt;
 *             &lt;enumeration value="Men-16"/&gt;
 *             &lt;enumeration value="Women-16"/&gt;
 *             &lt;enumeration value="Men-35"/&gt;
 *             &lt;enumeration value="Women-35"/&gt;
 *             &lt;enumeration value="Men-40"/&gt;
 *             &lt;enumeration value="Women-40"/&gt;
 *             &lt;enumeration value="Men-45"/&gt;
 *             &lt;enumeration value="Women-45"/&gt;
 *             &lt;enumeration value="Men-50"/&gt;
 *             &lt;enumeration value="Women-50"/&gt;
 *             &lt;enumeration value="Men-55"/&gt;
 *             &lt;enumeration value="Women-55"/&gt;
 *             &lt;enumeration value="Men-60"/&gt;
 *             &lt;enumeration value="Women-60"/&gt;
 *             &lt;enumeration value="Men-65"/&gt;
 *             &lt;enumeration value="Women-65"/&gt;
 *             &lt;enumeration value="Men-70"/&gt;
 *             &lt;enumeration value="Women-70"/&gt;
 *             &lt;enumeration value="Men-75"/&gt;
 *             &lt;enumeration value="Women-75"/&gt;
 *             &lt;enumeration value="Men-80"/&gt;
 *             &lt;enumeration value="Women-80"/&gt;
 *             &lt;enumeration value="Men-85"/&gt;
 *             &lt;enumeration value="Women-85"/&gt;
 *             &lt;enumeration value="Men-90"/&gt;
 *             &lt;enumeration value="Women-90"/&gt;
 *             &lt;enumeration value="Men-95"/&gt;
 *             &lt;enumeration value="Women-95"/&gt;
 *             &lt;enumeration value="Men-100"/&gt;
 *             &lt;enumeration value="Women-100"/&gt;
 *             &lt;enumeration value="NotSet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="championshipCompetitionFormat" default="NotSet"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Sprint"/&gt;
 *             &lt;enumeration value="Middle"/&gt;
 *             &lt;enumeration value="Long"/&gt;
 *             &lt;enumeration value="UltraLong"/&gt;
 *             &lt;enumeration value="PreO"/&gt;
 *             &lt;enumeration value="TempO"/&gt;
 *             &lt;enumeration value="Masstart"/&gt;
 *             &lt;enumeration value="Pursuit"/&gt;
 *             &lt;enumeration value="KnockOutSprint"/&gt;
 *             &lt;enumeration value="Relay"/&gt;
 *             &lt;enumeration value="SprintRelay"/&gt;
 *             &lt;enumeration value="MixedRelay"/&gt;
 *             &lt;enumeration value="Qualification"/&gt;
 *             &lt;enumeration value="NotSet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "championshipResultlistId",
    "championshipRaceSubType",
    "classResult"
})
@XmlRootElement(name = "ChampionshipResultlist")
public class ChampionshipResultlist {

    @XmlElement(name = "ChampionshipResultlistId", required = true)
    protected ChampionshipResultlistId championshipResultlistId;
    @XmlElement(name = "ChampionshipRaceSubType", required = true)
    protected ChampionshipRaceSubType championshipRaceSubType;
    @XmlElement(name = "ClassResult")
    protected List<ClassResult> classResult;
    @XmlAttribute(name = "raceClassName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String raceClassName;
    @XmlAttribute(name = "championshipCompetitionFormat")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String championshipCompetitionFormat;

    /**
     * Gets the value of the championshipResultlistId property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipResultlistId }
     *     
     */
    public ChampionshipResultlistId getChampionshipResultlistId() {
        return championshipResultlistId;
    }

    /**
     * Sets the value of the championshipResultlistId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipResultlistId }
     *     
     */
    public void setChampionshipResultlistId(ChampionshipResultlistId value) {
        this.championshipResultlistId = value;
    }

    /**
     * Gets the value of the championshipRaceSubType property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipRaceSubType }
     *     
     */
    public ChampionshipRaceSubType getChampionshipRaceSubType() {
        return championshipRaceSubType;
    }

    /**
     * Sets the value of the championshipRaceSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipRaceSubType }
     *     
     */
    public void setChampionshipRaceSubType(ChampionshipRaceSubType value) {
        this.championshipRaceSubType = value;
    }

    /**
     * Gets the value of the classResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassResult }
     * 
     * 
     */
    public List<ClassResult> getClassResult() {
        if (classResult == null) {
            classResult = new ArrayList<ClassResult>();
        }
        return this.classResult;
    }

    /**
     * Gets the value of the raceClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRaceClassName() {
        if (raceClassName == null) {
            return "NotSet";
        } else {
            return raceClassName;
        }
    }

    /**
     * Sets the value of the raceClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRaceClassName(String value) {
        this.raceClassName = value;
    }

    /**
     * Gets the value of the championshipCompetitionFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChampionshipCompetitionFormat() {
        if (championshipCompetitionFormat == null) {
            return "NotSet";
        } else {
            return championshipCompetitionFormat;
        }
    }

    /**
     * Sets the value of the championshipCompetitionFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChampionshipCompetitionFormat(String value) {
        this.championshipCompetitionFormat = value;
    }

}
