//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ChampionshipId"/&gt;
 *         &lt;element ref="{}ChampionshipPosition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "championshipId",
    "championshipPosition"
})
@XmlRootElement(name = "ChampionshipResult")
public class ChampionshipResult {

    @XmlElement(name = "ChampionshipId", required = true)
    protected ChampionshipId championshipId;
    @XmlElement(name = "ChampionshipPosition")
    protected ChampionshipPosition championshipPosition;

    /**
     * Gets the value of the championshipId property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipId }
     *     
     */
    public ChampionshipId getChampionshipId() {
        return championshipId;
    }

    /**
     * Sets the value of the championshipId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipId }
     *     
     */
    public void setChampionshipId(ChampionshipId value) {
        this.championshipId = value;
    }

    /**
     * Gets the value of the championshipPosition property.
     * 
     * @return
     *     possible object is
     *     {@link ChampionshipPosition }
     *     
     */
    public ChampionshipPosition getChampionshipPosition() {
        return championshipPosition;
    }

    /**
     * Sets the value of the championshipPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChampionshipPosition }
     *     
     */
    public void setChampionshipPosition(ChampionshipPosition value) {
        this.championshipPosition = value;
    }

}
