//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}EventId"/&gt;
 *         &lt;element ref="{}Name"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}EventClassificationId"/&gt;
 *           &lt;element ref="{}EventClassification"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}EventStatusId"/&gt;
 *           &lt;element ref="{}EventStatus"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{}EventAttributeId"/&gt;
 *           &lt;element ref="{}EventAttribute"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{}DisciplineId"/&gt;
 *           &lt;element ref="{}Discipline"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}StartDate"/&gt;
 *         &lt;element ref="{}FinishDate" minOccurs="0"/&gt;
 *         &lt;element ref="{}AlternativeDates" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}EventOfficial" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Organiser" minOccurs="0"/&gt;
 *         &lt;element ref="{}Championships" minOccurs="0"/&gt;
 *         &lt;element ref="{}Resultlists" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{}EventClass"/&gt;
 *           &lt;element ref="{}ClassType"/&gt;
 *           &lt;element ref="{}ClassTypeId"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}EntryBreak" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}EventRace" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}WebURL" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ContactData" minOccurs="0"/&gt;
 *         &lt;element ref="{}ServiceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Service" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ServiceRequest" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Comment" minOccurs="0"/&gt;
 *         &lt;element ref="{}ClassTypeComment" minOccurs="0"/&gt;
 *         &lt;element ref="{}PunchingUnitType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ModifyDate" minOccurs="0"/&gt;
 *         &lt;element ref="{}ModifiedBy" minOccurs="0"/&gt;
 *         &lt;element ref="{}HashTableEntry" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ParentEvent" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="eventForm" default="IndSingleDay"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="IndSingleDay"/&gt;
 *             &lt;enumeration value="IndMultiDay"/&gt;
 *             &lt;enumeration value="TeamSingleDay"/&gt;
 *             &lt;enumeration value="TeamMultiDay"/&gt;
 *             &lt;enumeration value="RelaySingleDay"/&gt;
 *             &lt;enumeration value="RelayMultiDay"/&gt;
 *             &lt;enumeration value="PatrolSingleDay"/&gt;
 *             &lt;enumeration value="PatrolMultiDay"/&gt;
 *             &lt;enumeration value="MasterEvent"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventId",
    "name",
    "eventClassificationId",
    "eventClassification",
    "eventStatusId",
    "eventStatus",
    "eventAttributeIdOrEventAttribute",
    "disciplineIdOrDiscipline",
    "startDate",
    "finishDate",
    "alternativeDates",
    "eventOfficial",
    "organiser",
    "championships",
    "resultlists",
    "eventClassOrClassTypeOrClassTypeId",
    "entryBreak",
    "eventRace",
    "webURL",
    "contactData",
    "serviceType",
    "service",
    "serviceRequest",
    "comment",
    "classTypeComment",
    "punchingUnitType",
    "modifyDate",
    "modifiedBy",
    "hashTableEntry",
    "parentEvent"
})
@XmlRootElement(name = "Event")
public class Event {

    @XmlElement(name = "EventId", required = true)
    protected EventId eventId;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "EventClassificationId")
    protected EventClassificationId eventClassificationId;
    @XmlElement(name = "EventClassification")
    protected EventClassification eventClassification;
    @XmlElement(name = "EventStatusId")
    protected EventStatusId eventStatusId;
    @XmlElement(name = "EventStatus")
    protected EventStatus eventStatus;
    @XmlElements({
        @XmlElement(name = "EventAttributeId", type = EventAttributeId.class),
        @XmlElement(name = "EventAttribute", type = EventAttribute.class)
    })
    protected List<Object> eventAttributeIdOrEventAttribute;
    @XmlElements({
        @XmlElement(name = "DisciplineId", type = DisciplineId.class),
        @XmlElement(name = "Discipline", type = Discipline.class)
    })
    protected List<Object> disciplineIdOrDiscipline;
    @XmlElement(name = "StartDate", required = true)
    protected StartDate startDate;
    @XmlElement(name = "FinishDate")
    protected FinishDate finishDate;
    @XmlElement(name = "AlternativeDates")
    protected List<AlternativeDates> alternativeDates;
    @XmlElement(name = "EventOfficial")
    protected List<EventOfficial> eventOfficial;
    @XmlElement(name = "Organiser")
    protected Organiser organiser;
    @XmlElement(name = "Championships")
    protected Championships championships;
    @XmlElement(name = "Resultlists")
    protected Resultlists resultlists;
    @XmlElements({
        @XmlElement(name = "EventClass", type = EventClass.class),
        @XmlElement(name = "ClassType", type = ClassType.class),
        @XmlElement(name = "ClassTypeId", type = ClassTypeId.class)
    })
    protected List<Object> eventClassOrClassTypeOrClassTypeId;
    @XmlElement(name = "EntryBreak")
    protected List<EntryBreak> entryBreak;
    @XmlElement(name = "EventRace")
    protected List<EventRace> eventRace;
    @XmlElement(name = "WebURL")
    protected List<WebURL> webURL;
    @XmlElement(name = "ContactData")
    protected ContactData contactData;
    @XmlElement(name = "ServiceType")
    protected List<ServiceType> serviceType;
    @XmlElement(name = "Service")
    protected List<Service> service;
    @XmlElement(name = "ServiceRequest")
    protected List<ServiceRequest> serviceRequest;
    @XmlElement(name = "Comment")
    protected Comment comment;
    @XmlElement(name = "ClassTypeComment")
    protected ClassTypeComment classTypeComment;
    @XmlElement(name = "PunchingUnitType")
    protected List<PunchingUnitType> punchingUnitType;
    @XmlElement(name = "ModifyDate")
    protected ModifyDate modifyDate;
    @XmlElement(name = "ModifiedBy")
    protected ModifiedBy modifiedBy;
    @XmlElement(name = "HashTableEntry")
    protected List<HashTableEntry> hashTableEntry;
    @XmlElement(name = "ParentEvent")
    protected ParentEvent parentEvent;
    @XmlAttribute(name = "eventForm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String eventForm;

    /**
     * Gets the value of the eventId property.
     * 
     * @return
     *     possible object is
     *     {@link EventId }
     *     
     */
    public EventId getEventId() {
        return eventId;
    }

    /**
     * Sets the value of the eventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventId }
     *     
     */
    public void setEventId(EventId value) {
        this.eventId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the eventClassificationId property.
     * 
     * @return
     *     possible object is
     *     {@link EventClassificationId }
     *     
     */
    public EventClassificationId getEventClassificationId() {
        return eventClassificationId;
    }

    /**
     * Sets the value of the eventClassificationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventClassificationId }
     *     
     */
    public void setEventClassificationId(EventClassificationId value) {
        this.eventClassificationId = value;
    }

    /**
     * Gets the value of the eventClassification property.
     * 
     * @return
     *     possible object is
     *     {@link EventClassification }
     *     
     */
    public EventClassification getEventClassification() {
        return eventClassification;
    }

    /**
     * Sets the value of the eventClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventClassification }
     *     
     */
    public void setEventClassification(EventClassification value) {
        this.eventClassification = value;
    }

    /**
     * Gets the value of the eventStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link EventStatusId }
     *     
     */
    public EventStatusId getEventStatusId() {
        return eventStatusId;
    }

    /**
     * Sets the value of the eventStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventStatusId }
     *     
     */
    public void setEventStatusId(EventStatusId value) {
        this.eventStatusId = value;
    }

    /**
     * Gets the value of the eventStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EventStatus }
     *     
     */
    public EventStatus getEventStatus() {
        return eventStatus;
    }

    /**
     * Sets the value of the eventStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventStatus }
     *     
     */
    public void setEventStatus(EventStatus value) {
        this.eventStatus = value;
    }

    /**
     * Gets the value of the eventAttributeIdOrEventAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventAttributeIdOrEventAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventAttributeIdOrEventAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventAttributeId }
     * {@link EventAttribute }
     * 
     * 
     */
    public List<Object> getEventAttributeIdOrEventAttribute() {
        if (eventAttributeIdOrEventAttribute == null) {
            eventAttributeIdOrEventAttribute = new ArrayList<Object>();
        }
        return this.eventAttributeIdOrEventAttribute;
    }

    /**
     * Gets the value of the disciplineIdOrDiscipline property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disciplineIdOrDiscipline property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisciplineIdOrDiscipline().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisciplineId }
     * {@link Discipline }
     * 
     * 
     */
    public List<Object> getDisciplineIdOrDiscipline() {
        if (disciplineIdOrDiscipline == null) {
            disciplineIdOrDiscipline = new ArrayList<Object>();
        }
        return this.disciplineIdOrDiscipline;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link StartDate }
     *     
     */
    public StartDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartDate }
     *     
     */
    public void setStartDate(StartDate value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the finishDate property.
     * 
     * @return
     *     possible object is
     *     {@link FinishDate }
     *     
     */
    public FinishDate getFinishDate() {
        return finishDate;
    }

    /**
     * Sets the value of the finishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinishDate }
     *     
     */
    public void setFinishDate(FinishDate value) {
        this.finishDate = value;
    }

    /**
     * Gets the value of the alternativeDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativeDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativeDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternativeDates }
     * 
     * 
     */
    public List<AlternativeDates> getAlternativeDates() {
        if (alternativeDates == null) {
            alternativeDates = new ArrayList<AlternativeDates>();
        }
        return this.alternativeDates;
    }

    /**
     * Gets the value of the eventOfficial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventOfficial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventOfficial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventOfficial }
     * 
     * 
     */
    public List<EventOfficial> getEventOfficial() {
        if (eventOfficial == null) {
            eventOfficial = new ArrayList<EventOfficial>();
        }
        return this.eventOfficial;
    }

    /**
     * Gets the value of the organiser property.
     * 
     * @return
     *     possible object is
     *     {@link Organiser }
     *     
     */
    public Organiser getOrganiser() {
        return organiser;
    }

    /**
     * Sets the value of the organiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organiser }
     *     
     */
    public void setOrganiser(Organiser value) {
        this.organiser = value;
    }

    /**
     * Gets the value of the championships property.
     * 
     * @return
     *     possible object is
     *     {@link Championships }
     *     
     */
    public Championships getChampionships() {
        return championships;
    }

    /**
     * Sets the value of the championships property.
     * 
     * @param value
     *     allowed object is
     *     {@link Championships }
     *     
     */
    public void setChampionships(Championships value) {
        this.championships = value;
    }

    /**
     * Gets the value of the resultlists property.
     * 
     * @return
     *     possible object is
     *     {@link Resultlists }
     *     
     */
    public Resultlists getResultlists() {
        return resultlists;
    }

    /**
     * Sets the value of the resultlists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultlists }
     *     
     */
    public void setResultlists(Resultlists value) {
        this.resultlists = value;
    }

    /**
     * Gets the value of the eventClassOrClassTypeOrClassTypeId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventClassOrClassTypeOrClassTypeId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventClassOrClassTypeOrClassTypeId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventClass }
     * {@link ClassType }
     * {@link ClassTypeId }
     * 
     * 
     */
    public List<Object> getEventClassOrClassTypeOrClassTypeId() {
        if (eventClassOrClassTypeOrClassTypeId == null) {
            eventClassOrClassTypeOrClassTypeId = new ArrayList<Object>();
        }
        return this.eventClassOrClassTypeOrClassTypeId;
    }

    /**
     * Gets the value of the entryBreak property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entryBreak property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntryBreak().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntryBreak }
     * 
     * 
     */
    public List<EntryBreak> getEntryBreak() {
        if (entryBreak == null) {
            entryBreak = new ArrayList<EntryBreak>();
        }
        return this.entryBreak;
    }

    /**
     * Gets the value of the eventRace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventRace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventRace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventRace }
     * 
     * 
     */
    public List<EventRace> getEventRace() {
        if (eventRace == null) {
            eventRace = new ArrayList<EventRace>();
        }
        return this.eventRace;
    }

    /**
     * Gets the value of the webURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the webURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWebURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WebURL }
     * 
     * 
     */
    public List<WebURL> getWebURL() {
        if (webURL == null) {
            webURL = new ArrayList<WebURL>();
        }
        return this.webURL;
    }

    /**
     * Gets the value of the contactData property.
     * 
     * @return
     *     possible object is
     *     {@link ContactData }
     *     
     */
    public ContactData getContactData() {
        return contactData;
    }

    /**
     * Sets the value of the contactData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactData }
     *     
     */
    public void setContactData(ContactData value) {
        this.contactData = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceType }
     * 
     * 
     */
    public List<ServiceType> getServiceType() {
        if (serviceType == null) {
            serviceType = new ArrayList<ServiceType>();
        }
        return this.serviceType;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the serviceRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceRequest }
     * 
     * 
     */
    public List<ServiceRequest> getServiceRequest() {
        if (serviceRequest == null) {
            serviceRequest = new ArrayList<ServiceRequest>();
        }
        return this.serviceRequest;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the classTypeComment property.
     * 
     * @return
     *     possible object is
     *     {@link ClassTypeComment }
     *     
     */
    public ClassTypeComment getClassTypeComment() {
        return classTypeComment;
    }

    /**
     * Sets the value of the classTypeComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassTypeComment }
     *     
     */
    public void setClassTypeComment(ClassTypeComment value) {
        this.classTypeComment = value;
    }

    /**
     * Gets the value of the punchingUnitType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the punchingUnitType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPunchingUnitType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PunchingUnitType }
     * 
     * 
     */
    public List<PunchingUnitType> getPunchingUnitType() {
        if (punchingUnitType == null) {
            punchingUnitType = new ArrayList<PunchingUnitType>();
        }
        return this.punchingUnitType;
    }

    /**
     * Gets the value of the modifyDate property.
     * 
     * @return
     *     possible object is
     *     {@link ModifyDate }
     *     
     */
    public ModifyDate getModifyDate() {
        return modifyDate;
    }

    /**
     * Sets the value of the modifyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifyDate }
     *     
     */
    public void setModifyDate(ModifyDate value) {
        this.modifyDate = value;
    }

    /**
     * Gets the value of the modifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link ModifiedBy }
     *     
     */
    public ModifiedBy getModifiedBy() {
        return modifiedBy;
    }

    /**
     * Sets the value of the modifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifiedBy }
     *     
     */
    public void setModifiedBy(ModifiedBy value) {
        this.modifiedBy = value;
    }

    /**
     * Gets the value of the hashTableEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hashTableEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHashTableEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HashTableEntry }
     * 
     * 
     */
    public List<HashTableEntry> getHashTableEntry() {
        if (hashTableEntry == null) {
            hashTableEntry = new ArrayList<HashTableEntry>();
        }
        return this.hashTableEntry;
    }

    /**
     * Gets the value of the parentEvent property.
     * 
     * @return
     *     possible object is
     *     {@link ParentEvent }
     *     
     */
    public ParentEvent getParentEvent() {
        return parentEvent;
    }

    /**
     * Sets the value of the parentEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentEvent }
     *     
     */
    public void setParentEvent(ParentEvent value) {
        this.parentEvent = value;
    }

    /**
     * Gets the value of the eventForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventForm() {
        if (eventForm == null) {
            return "IndSingleDay";
        } else {
            return eventForm;
        }
    }

    /**
     * Sets the value of the eventForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventForm(String value) {
        this.eventForm = value;
    }

}
