//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Time" minOccurs="0"/&gt;
 *         &lt;element ref="{}TimeDiff" minOccurs="0"/&gt;
 *         &lt;element ref="{}ResultPosition" minOccurs="0"/&gt;
 *         &lt;element ref="{}TeamStatus"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "time",
    "timeDiff",
    "resultPosition",
    "teamStatus"
})
@XmlRootElement(name = "OverallResult")
public class OverallResult {

    @XmlElement(name = "Time")
    protected Time time;
    @XmlElement(name = "TimeDiff")
    protected TimeDiff timeDiff;
    @XmlElement(name = "ResultPosition")
    protected ResultPosition resultPosition;
    @XmlElement(name = "TeamStatus", required = true)
    protected TeamStatus teamStatus;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     */
    public void setTime(Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the timeDiff property.
     * 
     * @return
     *     possible object is
     *     {@link TimeDiff }
     *     
     */
    public TimeDiff getTimeDiff() {
        return timeDiff;
    }

    /**
     * Sets the value of the timeDiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeDiff }
     *     
     */
    public void setTimeDiff(TimeDiff value) {
        this.timeDiff = value;
    }

    /**
     * Gets the value of the resultPosition property.
     * 
     * @return
     *     possible object is
     *     {@link ResultPosition }
     *     
     */
    public ResultPosition getResultPosition() {
        return resultPosition;
    }

    /**
     * Sets the value of the resultPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultPosition }
     *     
     */
    public void setResultPosition(ResultPosition value) {
        this.resultPosition = value;
    }

    /**
     * Gets the value of the teamStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TeamStatus }
     *     
     */
    public TeamStatus getTeamStatus() {
        return teamStatus;
    }

    /**
     * Sets the value of the teamStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamStatus }
     *     
     */
    public void setTeamStatus(TeamStatus value) {
        this.teamStatus = value;
    }

}
