//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}StatisticalInquiryParam" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}StatisticalResult" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="reportname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statisticalInquiryParam",
    "statisticalResult"
})
@XmlRootElement(name = "StatisticalReport")
public class StatisticalReport {

    @XmlElement(name = "StatisticalInquiryParam")
    protected List<StatisticalInquiryParam> statisticalInquiryParam;
    @XmlElement(name = "StatisticalResult")
    protected List<StatisticalResult> statisticalResult;
    @XmlAttribute(name = "reportname")
    @XmlSchemaType(name = "anySimpleType")
    protected String reportname;

    /**
     * Gets the value of the statisticalInquiryParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statisticalInquiryParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatisticalInquiryParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatisticalInquiryParam }
     * 
     * 
     */
    public List<StatisticalInquiryParam> getStatisticalInquiryParam() {
        if (statisticalInquiryParam == null) {
            statisticalInquiryParam = new ArrayList<StatisticalInquiryParam>();
        }
        return this.statisticalInquiryParam;
    }

    /**
     * Gets the value of the statisticalResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statisticalResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatisticalResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatisticalResult }
     * 
     * 
     */
    public List<StatisticalResult> getStatisticalResult() {
        if (statisticalResult == null) {
            statisticalResult = new ArrayList<StatisticalResult>();
        }
        return this.statisticalResult;
    }

    /**
     * Gets the value of the reportname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportname() {
        return reportname;
    }

    /**
     * Sets the value of the reportname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportname(String value) {
        this.reportname = value;
    }

}
