//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}TeamCompetitorId"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element ref="{}PersonId"/&gt;
 *           &lt;element ref="{}Person"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element ref="{}OrganisationId"/&gt;
 *           &lt;element ref="{}Organisation"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}CCard" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}TeamSequence" minOccurs="0"/&gt;
 *         &lt;element ref="{}TeamOrder" minOccurs="0"/&gt;
 *         &lt;element ref="{}EntryEntryFee" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teamCompetitorId",
    "personId",
    "person",
    "organisationId",
    "organisation",
    "cCard",
    "teamSequence",
    "teamOrder",
    "entryEntryFee"
})
@XmlRootElement(name = "TeamCompetitor")
public class TeamCompetitor {

    @XmlElement(name = "TeamCompetitorId", required = true)
    protected TeamCompetitorId teamCompetitorId;
    @XmlElement(name = "PersonId")
    protected PersonId personId;
    @XmlElement(name = "Person")
    protected Person person;
    @XmlElement(name = "OrganisationId")
    protected OrganisationId organisationId;
    @XmlElement(name = "Organisation")
    protected Organisation organisation;
    @XmlElement(name = "CCard")
    protected List<CCard> cCard;
    @XmlElement(name = "TeamSequence")
    protected TeamSequence teamSequence;
    @XmlElement(name = "TeamOrder")
    protected TeamOrder teamOrder;
    @XmlElement(name = "EntryEntryFee")
    protected List<EntryEntryFee> entryEntryFee;

    /**
     * Gets the value of the teamCompetitorId property.
     * 
     * @return
     *     possible object is
     *     {@link TeamCompetitorId }
     *     
     */
    public TeamCompetitorId getTeamCompetitorId() {
        return teamCompetitorId;
    }

    /**
     * Sets the value of the teamCompetitorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamCompetitorId }
     *     
     */
    public void setTeamCompetitorId(TeamCompetitorId value) {
        this.teamCompetitorId = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link PersonId }
     *     
     */
    public PersonId getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonId }
     *     
     */
    public void setPersonId(PersonId value) {
        this.personId = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the organisationId property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationId }
     *     
     */
    public OrganisationId getOrganisationId() {
        return organisationId;
    }

    /**
     * Sets the value of the organisationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationId }
     *     
     */
    public void setOrganisationId(OrganisationId value) {
        this.organisationId = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setOrganisation(Organisation value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the cCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CCard }
     * 
     * 
     */
    public List<CCard> getCCard() {
        if (cCard == null) {
            cCard = new ArrayList<CCard>();
        }
        return this.cCard;
    }

    /**
     * Gets the value of the teamSequence property.
     * 
     * @return
     *     possible object is
     *     {@link TeamSequence }
     *     
     */
    public TeamSequence getTeamSequence() {
        return teamSequence;
    }

    /**
     * Sets the value of the teamSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamSequence }
     *     
     */
    public void setTeamSequence(TeamSequence value) {
        this.teamSequence = value;
    }

    /**
     * Gets the value of the teamOrder property.
     * 
     * @return
     *     possible object is
     *     {@link TeamOrder }
     *     
     */
    public TeamOrder getTeamOrder() {
        return teamOrder;
    }

    /**
     * Sets the value of the teamOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamOrder }
     *     
     */
    public void setTeamOrder(TeamOrder value) {
        this.teamOrder = value;
    }

    /**
     * Gets the value of the entryEntryFee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entryEntryFee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntryEntryFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntryEntryFee }
     * 
     * 
     */
    public List<EntryEntryFee> getEntryEntryFee() {
        if (entryEntryFee == null) {
            entryEntryFee = new ArrayList<EntryEntryFee>();
        }
        return this.entryEntryFee;
    }

}
