//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.05 at 12:30:58 AM CEST 
//


package se.javajive.juniorleague.adapters.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}TeamName"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{}OrganisationId"/&gt;
 *           &lt;element ref="{}Organisation"/&gt;
 *           &lt;element ref="{}CountryId"/&gt;
 *           &lt;element ref="{}Country"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}BibNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{}StartTime" minOccurs="0"/&gt;
 *         &lt;element ref="{}TeamMemberStart" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teamName",
    "organisationIdOrOrganisationOrCountryId",
    "bibNumber",
    "startTime",
    "teamMemberStart"
})
@XmlRootElement(name = "TeamStart")
public class TeamStart {

    @XmlElement(name = "TeamName", required = true)
    protected TeamName teamName;
    @XmlElements({
        @XmlElement(name = "OrganisationId", type = OrganisationId.class),
        @XmlElement(name = "Organisation", type = Organisation.class),
        @XmlElement(name = "CountryId", type = CountryId.class),
        @XmlElement(name = "Country", type = Country.class)
    })
    protected List<Object> organisationIdOrOrganisationOrCountryId;
    @XmlElement(name = "BibNumber")
    protected BibNumber bibNumber;
    @XmlElement(name = "StartTime")
    protected StartTime startTime;
    @XmlElement(name = "TeamMemberStart")
    protected List<TeamMemberStart> teamMemberStart;

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link TeamName }
     *     
     */
    public TeamName getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamName }
     *     
     */
    public void setTeamName(TeamName value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the organisationIdOrOrganisationOrCountryId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organisationIdOrOrganisationOrCountryId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganisationIdOrOrganisationOrCountryId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganisationId }
     * {@link Organisation }
     * {@link CountryId }
     * {@link Country }
     * 
     * 
     */
    public List<Object> getOrganisationIdOrOrganisationOrCountryId() {
        if (organisationIdOrOrganisationOrCountryId == null) {
            organisationIdOrOrganisationOrCountryId = new ArrayList<Object>();
        }
        return this.organisationIdOrOrganisationOrCountryId;
    }

    /**
     * Gets the value of the bibNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BibNumber }
     *     
     */
    public BibNumber getBibNumber() {
        return bibNumber;
    }

    /**
     * Sets the value of the bibNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibNumber }
     *     
     */
    public void setBibNumber(BibNumber value) {
        this.bibNumber = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link StartTime }
     *     
     */
    public StartTime getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartTime }
     *     
     */
    public void setStartTime(StartTime value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the teamMemberStart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teamMemberStart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeamMemberStart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TeamMemberStart }
     * 
     * 
     */
    public List<TeamMemberStart> getTeamMemberStart() {
        if (teamMemberStart == null) {
            teamMemberStart = new ArrayList<TeamMemberStart>();
        }
        return this.teamMemberStart;
    }

}
